# Generated by Django 4.0.6 on 2022-08-05 13:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='닉네임')),
                ('password', models.CharField(max_length=128, null=True, verbose_name='패스워드')),
                ('email', models.EmailField(default='', max_length=100, unique=True, verbose_name='이메일')),
                ('latitude', models.FloatField(default=0.0, null=True, verbose_name='위도')),
                ('longitude', models.FloatField(default=0.0, null=True, verbose_name='경도')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('gender', models.CharField(blank=True, choices=[('1', '남자'), ('2', '여자')], max_length=5, null=True, verbose_name='성별')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='공개여부')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')], verbose_name='폰 번호')),
                ('introduction', models.TextField(blank=True, default='유저님의 마이 페이지입니다', null=True, verbose_name='자기 소개글')),
                ('address', models.TextField(blank=True, null=True, verbose_name='주소')),
                ('profile_img', models.URLField(blank=True, default='https://cdn.pixabay.com/photo/2017/09/25/13/12/cocker-spaniel-2785074__480.jpg', max_length=500, null=True, verbose_name='프로필 이미지')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('following_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('type', models.CharField(choices=[('1', '강아지'), ('2', '고양이'), ('3', '기타')], max_length=5, verbose_name='종류')),
                ('gender', models.CharField(choices=[('1', '남자'), ('2', '여자'), ('3', '모름')], default='3', max_length=5, verbose_name='성별')),
                ('size', models.CharField(choices=[('1', '소형'), ('2', '중형'), ('3', '대형')], max_length=5, verbose_name='사이즈')),
                ('pet_profile_img', models.URLField(blank=True, default='https://cdn.pixabay.com/photo/2017/09/25/13/12/cocker-spaniel-2785074__480.jpg', null=True, verbose_name='프로필 이미지')),
                ('article', models.ManyToManyField(to='article.article', verbose_name='게시물')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
