# Generated by Django 4.0.6 on 2022-08-05 13:20

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkingMate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('start_date', models.DateField(null=True, verbose_name='날짜')),
                ('start_time', models.DateTimeField(verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(verbose_name='종료 시간')),
                ('region', models.CharField(max_length=30, verbose_name='지역')),
                ('place', models.CharField(max_length=200, verbose_name='만남 장소')),
                ('gender', models.CharField(max_length=10, verbose_name='참여자 성별')),
                ('size', models.CharField(max_length=30, verbose_name='사이즈')),
                ('people_num', models.CharField(max_length=20, verbose_name='참여자수')),
                ('contents', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='내용')),
                ('status', models.BooleanField(default=True, verbose_name='')),
                ('attending_user', models.ManyToManyField(blank=True, related_name='program', to=settings.AUTH_USER_MODEL, verbose_name='참여자 명단')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to=settings.AUTH_USER_MODEL, verbose_name='호스트')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
